# Generated by Django 3.1.4 on 2021-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Publication date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-publication_date',),
                'get_latest_by': 'publication_date',
                'unique_together': {('title', 'publication_date')},
            },
        ),
    ]
