# Generated by Django 3.1.4 on 2021-04-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionProblem',
        ),
    ]
