# Generated by Django 3.1.4 on 2021-06-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_squashed_0004_auto_20210421_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('id',), 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
    ]
