# Generated by Django 3.1.4 on 2021-04-21 18:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_delete_competitionproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(default=django.db.models.expressions.Value(''), verbose_name='Description'),
        ),
    ]
