# Generated by Django 3.1.4 on 2021-04-29 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('groups', '0001_initial'), ('groups', '0002_auto_20210208_2120'), ('groups', '0003_auto_20210223_1638'), ('groups', '0004_auto_20210223_1643'), ('groups', '0005_auto_20210311_1759'), ('groups', '0006_auto_20210421_2036'), ('groups', '0007_auto_20210424_1537'), ('groups', '0008_auto_20210429_1731')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('judge', '0001_squashed_0021_auto_20210429_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group name')),
                ('description', models.TextField(verbose_name='Group description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TE', 'Teacher'), ('SD', 'Student')], max_length=2, verbose_name='Role')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
