# Generated by Django 3.1.4 on 2021-06-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_squashed_0008_auto_20210429_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('pk',), 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupuser',
            options={'verbose_name': 'User group', 'verbose_name_plural': 'User groups'},
        ),
    ]
