# Generated by Django 3.1.4 on 2021-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='role',
            field=models.CharField(choices=[('TE', 'Teacher'), ('SD', 'Student')], max_length=2),
        ),
    ]
