# Generated by Django 3.1.4 on 2021-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210223_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
