# Generated by Django 3.1.4 on 2021-03-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210223_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionproblem',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionproblem',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='CompetitionProblem',
        ),
    ]
