# Generated by Django 3.1.4 on 2021-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210311_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Group description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='role',
            field=models.CharField(choices=[('TE', 'Teacher'), ('SD', 'Student')], max_length=2, verbose_name='Role'),
        ),
    ]
