# Generated by Django 3.1.4 on 2021-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_squashed_0021_auto_20210429_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(max_length=30),
        ),
    ]
