# Generated by Django 3.1.4 on 2020-12-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solving_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CE', 'Compilation error'), ('PA', 'Partially accepted'), ('AC', 'Accepted')], max_length=2)),
                ('program_code', models.TextField()),
                ('avg_memory_usage', models.CharField(max_length=30)),
                ('avg_time_usage', models.CharField(max_length=30)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_usage', models.CharField(max_length=30)),
                ('time_usage', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('CE', 'Compilation error'), ('PA', 'Partially accepted'), ('AC', 'Accepted')], max_length=2)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_photo', models.ImageField(upload_to='')),
                ('difficulty', models.CharField(choices=[('VE', 'Very easy'), ('EA', 'Easy'), ('MD', 'Middle'), ('HD', 'Hard'), ('VH', 'Very hard')], max_length=2)),
                ('classification', models.CharField(choices=[('CB', 'Combinatorics')], max_length=2)),
                ('input_condition', models.CharField(max_length=500, verbose_name='Input')),
                ('output_condition', models.CharField(max_length=500, verbose_name='Output')),
                ('special_warning', models.CharField(max_length=500, null=True, verbose_name='Warning')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_input', models.TextField(verbose_name='Sample output #')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('memory_limit', models.CharField(max_length=30)),
                ('time_limit', models.CharField(max_length=30)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.programminglanguage')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.task')),
            ],
        ),
        migrations.DeleteModel(
            name='CodeFile',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='solutiontest',
            name='task_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.tasktest'),
        ),
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.task'),
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
