# Generated by Django 3.1.4 on 2021-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210429_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('-solving_date',), 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='classification',
            field=models.CharField(choices=[('CB', 'Combinatorics'), ('BS', 'Breadth-first-search')], max_length=2),
        ),
        migrations.AlterField(
            model_name='problem',
            name='classification_en',
            field=models.CharField(choices=[('CB', 'Combinatorics'), ('BS', 'Breadth-first-search')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='classification_uk',
            field=models.CharField(choices=[('CB', 'Combinatorics'), ('BS', 'Breadth-first-search')], max_length=2, null=True),
        ),
    ]
