# Generated by Django 3.1.4 on 2020-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20201224_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('AC', 'Accepted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solutiontest',
            name='status',
            field=models.CharField(choices=[('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('AC', 'Accepted')], max_length=2),
        ),
    ]
