# Generated by Django 3.1.4 on 2021-01-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20201226_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('JG', 'Judging'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solutiontest',
            name='status',
            field=models.CharField(choices=[('JG', 'Judging'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
    ]
