# Generated by Django 3.1.4 on 2021-01-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20210116_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='compile',
            field=models.CharField(default='cpp', max_length=300),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='execute',
            field=models.CharField(default='cpp', max_length=300),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='extension',
            field=models.CharField(default='cpp', max_length=5),
        ),
    ]
