# Generated by Django 3.1.4 on 2021-01-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20210116_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='compile',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='execute',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='extension',
            field=models.CharField(max_length=5),
        ),
    ]
