# Generated by Django 3.1.4 on 2021-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_remove_tasktest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solutiontest',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
    ]
