# Generated by Django 3.1.4 on 2021-02-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20210129_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionproblem',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='groupcompetition',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='CompetitionProblem',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupCompetition',
        ),
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
