# Generated by Django 3.1.4 on 2021-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20210202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('RE', 'Runtime error'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solutiontest',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('RE', 'Runtime error'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2),
        ),
    ]
