# Generated by Django 3.1.4 on 2021-03-27 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0012_auto_20210208_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CE', 'Compilation error'), ('WA', 'Wrong answer'), ('RE', 'Runtime error'), ('PA', 'Partially accepted'), ('TO', 'Timeout'), ('MO', 'Memory out'), ('AC', 'Accepted')], max_length=2)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
