# Generated by Django 3.1.4 on 2021-04-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_delete_competitionproblem'),
        ('judge', '0013_userproblemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='competition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='competitions.competition'),
        ),
    ]
