# Generated by Django 3.1.4 on 2021-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_auto_20210409_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='classification_en',
            field=models.CharField(choices=[('CB', 'Combinatorics')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='classification_ua',
            field=models.CharField(choices=[('CB', 'Combinatorics')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty_en',
            field=models.CharField(choices=[('VE', 'Very easy'), ('EA', 'Easy'), ('MD', 'Middle'), ('HD', 'Hard'), ('VH', 'Very hard')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty_ua',
            field=models.CharField(choices=[('VE', 'Very easy'), ('EA', 'Easy'), ('MD', 'Middle'), ('HD', 'Hard'), ('VH', 'Very hard')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_condition_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Input'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_condition_ua',
            field=models.CharField(max_length=500, null=True, verbose_name='Input'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_condition_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_condition_ua',
            field=models.CharField(max_length=500, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='problem',
            name='special_warning_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Warning'),
        ),
        migrations.AddField(
            model_name='problem',
            name='special_warning_ua',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Warning'),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_ua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problemsamples',
            name='sample_input_en',
            field=models.TextField(null=True, verbose_name='Sample input #'),
        ),
        migrations.AddField(
            model_name='problemsamples',
            name='sample_input_ua',
            field=models.TextField(null=True, verbose_name='Sample input #'),
        ),
        migrations.AddField(
            model_name='problemsamples',
            name='sample_output_en',
            field=models.TextField(null=True, verbose_name='Sample output #'),
        ),
        migrations.AddField(
            model_name='problemsamples',
            name='sample_output_ua',
            field=models.TextField(null=True, verbose_name='Sample output #'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Programming language'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='name_ua',
            field=models.TextField(null=True, verbose_name='Programming language'),
        ),
    ]
