# Generated by Django 3.1.4 on 2021-04-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_auto_20210421_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='classification_ua',
            new_name='classification_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='difficulty_ua',
            new_name='difficulty_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='input_condition_ua',
            new_name='input_condition_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='output_condition_ua',
            new_name='output_condition_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='special_warning_ua',
            new_name='special_warning_uk',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='problemsamples',
            old_name='sample_input_ua',
            new_name='sample_input_uk',
        ),
        migrations.RenameField(
            model_name='problemsamples',
            old_name='sample_output_ua',
            new_name='sample_output_uk',
        ),
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
