# Generated by Django 3.1.4 on 2021-04-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_auto_20210421_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='name_uk',
        ),
    ]
