# Generated by Django 3.1.4 on 2021-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_auto_20210421_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solving_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Solving date'),
        ),
    ]
